services:
  db:
    image: mysql
    restart: on-failure
    hostname: "mysqldb"
    healthcheck:
      test: "exit 0"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ezxam
      MYSQL_USER: user
      MYSQL_PASSWORD: 123Stella
    command:
      - --skip-log-bin
    ports:
      - "3307:3306"
    volumes:
      - "ezxam:/var/lib/mysql"

  ezxam:
    image: ezxam
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ezxam?allowPublicKeyRetrieval=true&useSSL=false

volumes:
  ezxam: